coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url
    - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
      value: "true"
    # - name: CODER_ACCESS_URL
    #   value: "https://coder.example.com"
  resources:
    limits:
        cpu: 500m
        memory: 1024Mi
    requests:
        cpu: 500m
        memory: 1024Mi
